### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by starwarsfreak219** [playajames419/OraxenTransparentBlocks#2]
Server Version: PaperMC 1.18.1
Oraxen Version: 1.121.0
OraxenTransparentBlocks Version: 1.1.1-SNAPSHOT
WorldGuard Version: 7.0.6+1cff55f
WorldEdit Version: 7.2.8+6008-1246d61

Hello, I was recently testing this plugin add-on for Oraxen, and unfortunately the plugin appears to disable itself on server startup with this error: https://paste.helpch.at/avoyapexob.md

Is there anything I am doing wrong on setting this up? Or is there a compatibility issue with the latest version of Oraxen? Thanks in advance!

**Comment by playajames419** [comment]
This plugin is no longer updated. Oraxen has implemented the feature this plugin offers. Look into the furniture mechanic within oraxen.
